name: Internal Release

on:
  push:
    branches:
      - 'internal'

jobs:
  build-and-release:
    name: Build & Publish to Internal
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/sukun.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release AAB
        env:
          STORE_FILE: sukun.jks
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew bundleRelease

      - name: Upload AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-aab-internal
          path: app/build/outputs/bundle/release/*.aab
          retention-days: 7

      - name: Upload to Play Store (Internal Testing)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: dhanfinix.android.sukun
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          status: completed
          whatsNewDirectory: whatsnew
